name: PR

on:
  pull_request:
    paths:
      - "**/*.novaextension/**"
      - ".github/workflows/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "build.mjs"
      - "types/**"

jobs:
  oxc-tools:
    uses: ./.github/workflows/validate-extension.yml
    with:
      extension-path: Oxc Tools.novaextension
